animal = input("What's your favorite animal? ").lower( )
print("Why did the " + animal + " cross the road?")
animal = input("What's your favorite animal? ")
animal = animal.lower( )
print("Why did the " + animal + " cross the road?")
animal = input("What's your favorite animal? ")
print("Why did the " + animal.lower( ) + " cross the road?")
